spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/user_db  # Docker로 띄운 postgresql_user의 DB URL
    username: user_user  # docker-compose.yml에 정의한 사용자 이름
    password: user_password  # docker-compose.yml에 정의한 비밀번호
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


server:
  port: 19095

auth:
  service:
    url: http://localhost:19092