spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accessShield
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


server:
  port: 19095

auth:
  service:
    url: http://localhost:19092