server:
  port: 19091
  tomcat:
    max-http-header-size: 16384

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
#        - id: gateway-service
#          uri: lb://gateway-service
#          predicates:
#            - Path=/api/**
#          filters:
#            - name: AuthFilter
#              args:
#                excludePaths:
#                  - /api/user/register
#                  - /api/user/login
#                  - /api/auth/login
#                  - /api/auth/reIssue
#                  - /api/auth/verify
#                  - /api/auth/logout
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/user/**
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - /api/user/login
                  - /api/user/register
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - /api/auth/login
                  - /api/auth/register
        - id: gateway-service
          uri: lb://gateway-service
          predicates:
            - Path=/api/**
          filters:
            - name: AuthFilter
              args:
                excludePaths:
                  - /api/user/register
                  - /api/user/login
                  - /api/auth/login
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG